NDefines.NGraphics.GRADIENT_BORDERS_FIELD_COUNTRY_LOW = 20.0
NDefines.NGraphics.GRADIENT_BORDERS_FIELD_COUNTRY_HIGH = 2000.0
NDefines.NGraphics.GRADIENT_BORDERS_THICKNESS_COUNTRY_LOW = 0.5
NDefines.NGraphics.GRADIENT_BORDERS_COUNTRY_CENTER_THICKNESS = 1.0
NDefines.NGraphics.GRADIENT_BORDERS_THICKNESS_COUNTRY_HIGH = 15.0
NDefines.NGraphics.GMT_OFFSET = 2293
NDefines.NGraphics.NORTH_POLE_OFFSET = 0.17
NDefines.NFrontend.CAMERA_MAX_HEIGHT = 3900.0